### ISSUE TITLE
Bindings still don't apply presets, but instead just refresh them

### ISSUE THREAD

**Issue by s4p1ence** [Mrcubix/Preset.Binding#4]
### **System:** 
- OS: Windows 10 Pro 22H2 build 19045.5487
- OpenTablet version: v0.6.5.1
- Tablet: XP-Pen Deco Pro Medium

Same as previous issues, not sure why i'm getting it after the fix. I have 4 different presets that i've bound to aux buttons on my tablet in each preset present. Presets don't switch on binds press. Anything else i can provide?

![Image](https://github.com/user-attachments/assets/13acda4b-35e4-4337-be0c-59711f67585a)

![Image](https://github.com/user-attachments/assets/aaf04799-ed65-4f84-b438-987a8c577f90)

**Comment by s4p1ence** [comment]
Okay, i did some Trial & Error here and it seems that pluging my tablet in USB 3.0 ports in my motherboard cause this issue. Using USB 2.0 the issue is gone for now and presets are switching with no problems whatsoever.

![Image](https://github.com/user-attachments/assets/76c43f18-3dcb-4334-becf-cc20d7558886)

**Comment by s4p1ence** [comment]
Nevermind, the issue appeared again after i connected my tablet once again today. I wonder what causes that, since it actually managed to work properly before

**Comment by s4p1ence** [comment]
A couple of reinstallations later, i've managed to make it work again, until i restarted OTD and everything got screwed up again. I wonder if it's related to the OTD's memory leak you've mentioned in previous issues.

Console log after a fresh installation of plugin (presets are switching out of the box with no problems):
![Image](https://github.com/user-attachments/assets/af682713-2ba2-4a0b-95a2-571a7145b955)
Console log after i reopened OTD (trying to switch presets, no use):
![Image](https://github.com/user-attachments/assets/7b554aed-e334-4863-9e86-320bb00175f8)

**Comment by Mrcubix** [comment]
My PR on plugin disposal was merged right before 0.6.5.1, so a lot of plugin memory leaks were fixed, now some still remains.
I doubt this is one of them.

Restart OTD & export a diagnostic.

FYI, if you don't see this message in the debug display (bottom left of console tab), that means there is a large issue still going on somehow : 

![Image](https://github.com/user-attachments/assets/e175f1b5-3e36-40b6-bbca-8c78ca1e00a0)

And i'm not able to replicate it in the latest release.

**Comment by s4p1ence** [comment]
Yup, can't see the message in debug. Here's the diagnostics

[diag.json](https://github.com/user-attachments/files/19095074/diag.json)

**Comment by Mrcubix** [comment]
![Image](https://github.com/user-attachments/assets/f7652aa2-1bc7-4b3d-b689-b4c1e1b9260a)

A reboot is in order to see properly what's going on

**Comment by Mrcubix** [comment]
https://github.com/Mrcubix/Preset.Binding/actions/runs/13683675447/artifacts/2698606884 (scroll down for artifacts)

Figured i also didn't create a new release i na while so give this build a try

**Comment by s4p1ence** [comment]
From what I've tested, this build is way more stable for me, don't have to reinstall anything in order to get it working on OTD restart. Though occasionally, i get these error messages

![Image](https://github.com/user-attachments/assets/e4e3c7dd-348e-471e-92e2-c745fbb244de)

![Image](https://github.com/user-attachments/assets/47a3c499-6c4c-4fd8-beb9-7c6dcd57f036)

**Comment by Mrcubix** [comment]
Going in the right direction then, i'll see how to properly fix this tomorrow then

**Comment by Mrcubix** [comment]
The exception in the second screenshot isn't expected, since it would mean that the daemon died, except the plugin is running on the daemon so it should had also died, so it doesn't make much sense.

As for the first screenshot, these could be happening if you spam too much? i might add a delay to prevent issues like these.

**Comment by Mrcubix** [comment]
Give this build a try, filtered out some exceptions & added a timeout delay between preset changes

https://github.com/Mrcubix/Preset.Binding/actions/runs/13704922249/artifacts/2705574665

**Comment by s4p1ence** [comment]
Just checked the last build, bindings work as intended, but i have a small issue with the preset binds not working half of the times on initial OTD launch so i have to manually change preset and then they start to work properly again. 

Here's a console log on fresh launch, and as you can see on the second pic, the lastly used config has the presets bound to the buttons, but pressing them doesn't do anything, doesn't even print anything to console. Loading any preset fixes the issue and the plugin starts working normally again. And again, it does work properly sometimes, but most of the times it doesn't. Weird.

![Image](https://github.com/user-attachments/assets/fdd941a3-dcbd-4216-80e2-9a689ac8395f)

![Image](https://github.com/user-attachments/assets/6b955c13-10b1-45d5-99c2-43312d1fb2bb)

**Comment by Mrcubix** [comment]
At this point, not much can be done except listing out potential causes : 
- Are you using a custom ISO OR partially debloated Windows ?
- It could be an issue related to specific tablets,
- I have only ever seen people encounter this issue on Arch Wayland & afaik, it was fixed with my PR to OTD.

I'm just unable to replicate this issue.

The plugin worked on all my systems & VMs i had tested the plugin on including : 

- My old physical Windows 8.1 Machine i was bringing to University,
- My personnal Windows 10 Install,
- My personnal Mint Install,
- My TV connected Raspberry pi 4B (Yes it works even on a slow ARM device) using my wireless CTH-471,
- A more used Windows 10 22H2 VM (used for Manufacturer Driver Behavior RE),
- A clean Windows 10 21H2 VM (used to test the touch API),
- A X11 Arch Install.

**Comment by s4p1ence** [comment]
Yeah, i did debloat my system a few years ago, but i'm afraid i won't be able to tell exaclty what tweaks may caused this and it's not that big of an issue for me anyway. Good thing it runs well on quite lots of systems you have!

**Comment by BlueGuitarCL** [comment]
I can confirm this still occurs on my setup. Seems to be pretty hit-or-miss, because what i've been doing since the last time i troubleshooted #2 was to load one of all the presets i intended to use first, and then start to use the Aux buttons to load them as desired; but today i stumbled upon not being able to use the Aux bindings to presets when the UX haven't been launched since the Daemon startup.

Some notable lines on today's troubleshooting:
- OS: ArchLinux Wayland (Niri WM, 25.02)
- OTD: Release 0.6.5.1
- Plugins:
    - Preset.Binding: CI Build/Github Action "Build Plugin" °9 on `master` branch (commit `e4825b5`)
    - https://github.com/Mrcubix/OTD.UX.Remote CI Build/Github Action "Build Plugin" °8 on `master` branch (commit `c54ea56`)
    - https://github.com/Kuuuube/Hover_Distance_Limiter Release 0.1.3
```
Mar 10 19:06:29 a5rch otd-daemon[91511]: [Wacom CTL-4100WL:Info]        Express Key Bindings: OTD.PresetBinds.Binding.PresetBinding, OTD.PresetBinds.Binding.PresetBinding, OTD.PresetBinds.Binding.PresetBinding,
Mar 10 19:06:29 a5rch otd-daemon[91511]: [IPC:Debug]        Connected to a client.
Mar 10 19:06:29 a5rch otd-daemon[91511]: [Wacom CTL-4100WL:Info]        Filters: Hover_Distance_Limiter.Hover_Distance_Limiter
Mar 10 19:06:29 a5rch otd-daemon[91511]: [Settings:Info]        Driver is enabled.
Mar 10 19:06:29 a5rch otd-daemon[91511]: [IPC:Debug]        Connected to a client. (x2)
Mar 10 19:06:29 a5rch otd-daemon[91511]: [IPC:Debug]        Disconnected from a client. (x3)
Mar 10 19:06:32 a5rch otd-daemon[91511]: [AggregateException:Error]        A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Connection reset by peer)
Mar 10 19:10:49 a5rch systemd[1191]: opentabletdriver.service: Consumed 2min 8.123s CPU time, 71.4M memory peak.
// next lines after reloading the Daemon with OTD.UX.Gtk closed
Mar 10 19:10:50 a5rch otd-daemon[91809]: [Wacom CTL-4100WL:Info]        Filters: Hover_Distance_Limiter.Hover_Distance_Limiter
Mar 10 19:10:50 a5rch otd-daemon[91809]: [Settings:Info]        Driver is enabled.
Mar 10 19:10:50 a5rch otd-daemon[91809]: [IPC:Debug]        Connected to a client.
Mar 10 19:10:51 a5rch otd-daemon[91809]: [AggregateException:Error]        A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Exception has been thrown by the target of an invocation.)
Mar 10 19:10:51 a5rch otd-daemon[91809]: [AggregateException:Error]        A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (This operation is not allowed after listening for messages has started.)
Mar 10 19:10:51 a5rch otd-daemon[91809]: [IPC:Debug]        Disconnected from a client.
Mar 10 19:10:51 a5rch otd-daemon[91809]: [IPC:Debug]        Disconnected from a client.
// here i start trying to load presets through the Aux buttons, nothing changes
Mar 10 19:12:38 a5rch otd-daemon[91809]: [Settings:Info]        Loaded preset 'ctl4100wl-relGame.json'
Mar 10 19:12:38 a5rch otd-daemon[91809]: [Settings:Info]        Loaded preset 'ctl4100wl_artist_HDMI-A-1.json'
Mar 10 19:12:38 a5rch otd-daemon[91809]: [Settings:Info]        Loaded preset 'ctl4100wl-artistFull.json'
Mar 10 19:12:38 a5rch otd-daemon[91809]: [Settings:Info]        Loaded preset 'ctl4100wl_artist_eDP-1.json'
Mar 10 19:13:38 a5rch otd-daemon[91809]: [Settings:Info]        Presets have been refreshed. Loaded 4 presets.
// last 4 lines (x3). Next, i did open up OTD.UX.Gtk
Mar 10 19:13:31 a5rch otd-daemon[91809]: [IPC:Debug]        Connected to a client.
Mar 10 19:13:31 a5rch otd-daemon[91809]: [Plugin:Debug]        Loading plugin 'Preset.Binding'
Mar 10 19:13:31 a5rch otd-daemon[91809]: [Plugin:Debug]        Loading plugin 'Hover Distance Limiter'
Mar 10 19:13:31 a5rch otd-daemon[91809]: [Plugin:Debug]        Loading plugin 'UX.Remote'
Mar 10 19:13:31 a5rch otd-daemon[91809]: [UX Remote:Info]        UX Remote started successfully.
// but still no changes. 3 tries again on the Aux and logging the 'Presets have been refreshed' bunch, but on a 4th try here i applied the preset through the UX, and it worked:
Mar 10 19:13:59 a5rch otd-daemon[91809]: [Evdev:Debug]        Successfully initialized virtual pressure sensitive tablet. (code NONE)
Mar 10 19:13:59 a5rch otd-daemon[91809]: [Wacom CTL-4100WL:Info]        Output mode: Artist Mode
Mar 10 19:13:59 a5rch otd-daemon[91809]: [Wacom CTL-4100WL:Info]        Display area: [1920x1080@<960, 540>:0°],
Mar 10 19:13:59 a5rch otd-daemon[91809]: [Wacom CTL-4100WL:Info]        Tablet area: [152x85.5@<76, 47.5>:0°],
Mar 10 19:13:59 a5rch otd-daemon[91809]: [Wacom CTL-4100WL:Info]        Clipping: Enabled
Mar 10 19:13:59 a5rch otd-daemon[91809]: [Wacom CTL-4100WL:Info]        Ignoring reports outside area: Disabled
Mar 10 19:13:59 a5rch otd-daemon[91809]: [Wacom CTL-4100WL:Info]        Pen Bindings: OpenTabletDriver.Desktop.Binding.LinuxArtistMode.LinuxArtistModeButtonBinding, OpenTabletDriver.Desktop.Binding.LinuxArtistMode.LinuxArtistModeButtonBinding
Mar 10 19:13:59 a5rch otd-daemon[91809]: [Wacom CTL-4100WL:Info]        Express Key Bindings: , OTD.PresetBinds.Binding.PresetBinding, OTD.PresetBinds.Binding.PresetBinding, OTD.PresetBinds.Binding.PresetBinding
Mar 10 19:13:59 a5rch otd-daemon[91809]: [Wacom CTL-4100WL:Info]        Filters: Hover_Distance_Limiter.Hover_Distance_Limiter
Mar 10 19:13:59 a5rch otd-daemon[91809]: [Settings:Info]        Driver is enabled.
Mar 10 19:13:59 a5rch otd-daemon[91809]: [Settings:Info]        Applied preset 'ctl4100wl_artist_HDMI-A-1'
// but sometimes it stops to work unexpectedly and there's no useful hints aside of what i've already shown here.
```
I suspect this might be due to something working unexpectedly somewhere between the Gtk UX, both of your plugins (UX.Remote, Preset.Binding), and the OTD.Daemon itself. I actually got a memleak on the UX while testing lol.

![Image](https://github.com/user-attachments/assets/252fab09-f6a6-4a8b-a11e-de942963d351)

Lines from when i got the memleak sent by the daemon btw:
```
Mar 10 19:19:02 a5rch otd-daemon[92421]: [AggregateException:Error]        A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The JSON-RPC connection with the remote party was lost before the request could complete.) (x4)
Mar 10 19:19:02 a5rch otd-daemon[92421]: [AggregateException:Error]        A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Cannot access a disposed object.
Mar 10 19:19:02 a5rch otd-daemon[92421]: Object name: 'StreamJsonRpc.JsonRpc'.)
Mar 10 19:19:02 a5rch otd-daemon[92421]: [AggregateException:Error]        A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The JSON-RPC connection with the remote party was lost before the request could complete.)
// iirc i closed the UX here while it was still on the "Connecting to OTD Daemon.." screen without prompting the Timeout dialog
Mar 10 19:19:34 a5rch otd-daemon[92421]: [AggregateException:Error]        A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Connection reset by peer)
```

**Comment by Mrcubix** [comment]
Disable UX.Remote, restart the UX & Daemon, then try again.
(Not able to replicate any of the issues using your comments)

Also if you can replicate it consistantly without UX.Remote, create a new issue & provide the steps again.

UPDATE: @BlueGuitarCL Give this build of UX.Remote a try https://github.com/Mrcubix/OTD.UX.Remote/actions/runs/13797854054

**Comment by Mrcubix** [comment]
Both give this artifact a try : https://github.com/Mrcubix/Preset.Binding/actions/runs/13798644138
Provide a diag if the problem persist.

**Comment by BlueGuitarCL** [comment]
@Mrcubix Here my latest log with comments, hope they're useful enough.
[Preset.Binding-issue4-b10_blueguitarcl-test0_OTD-v0.6.5.1_UX.Remote-b9.log](https://github.com/user-attachments/files/19200959/Preset.Binding-issue4-b10_blueguitarcl-test0_OTD-v0.6.5.1_UX.Remote-b9.log)
Shall we start trying to troubleshoot with the help of debug symbols again as on #2 ?

**Comment by s4p1ence** [comment]
> Both give this artifact a try : https://github.com/Mrcubix/Preset.Binding/actions/runs/13798644138 Provide a diag if the problem persist.

The issue still persists(?), though, from my tests, it got much less frequent. I only encountered it once and couldn't get it again after i replugged my tablet. Here's diagnostics

[s4p1ence_diag.json](https://github.com/user-attachments/files/19204993/s4p1ence_diag.json)

**Comment by Mrcubix** [comment]
@BlueGuitarCL could you open a separate issue as your problems are different & most likely related to UX.Remote

By the way, there is another plugin of mine for scrolling called `Scroll Binding` (Surprise) which provides high precision scrolling with keys on linux.

**Comment by Mrcubix** [comment]
As for your issue @s4p1ence , bruh 

![Image](https://github.com/user-attachments/assets/49be354f-4f52-4013-991d-72f8c16404f4)

All that remains seems to be from an bug somewhere outside of my control

**Comment by Mrcubix** [comment]
New Action build to be tested, relying less on a method, see if at least give us a proper stacktrace.

https://github.com/Mrcubix/Preset.Binding/actions/runs/13818769294

**Comment by Mrcubix** [comment]
Rewrote the plugin, needs testing now : 

https://github.com/Mrcubix/Preset.Binding/actions/runs/14576053514

**Comment by wareya** [comment]
I experienced this problem and the build in the actions run in the last comment before this one fixes it in terms of functionality, but the UI state of the OTD GUI frontend doesn't update.

**Comment by Mrcubix** [comment]
The UX won't update on its own, [UX.Remote](https://github.com/Mrcubix/OTD.UX.Remote/actions/runs/13797854054) is required for that (and is purely optional as its only use is to update the UX, which most don't need anyway).

If it still doesn't update after installing it & restarting the daemon as well as the UX, then export diagnostics (Help > Export Diagnostics) & upload the log part here.

**Comment by wareya** [comment]
After installing that and setting it up on my presets and fully restarting everything, everything fully works for me 👍

**Comment by K1aymore** [comment]
> Rewrote the plugin, needs testing now :
> 
> https://github.com/Mrcubix/Preset.Binding/actions/runs/14576053514

I had a similar issue, where it would refresh the presets but not switch between them. I installed this version and now it works great.

OS: NixOS Unstable with KDE Plasma Wayland 6.4.2
OTD: v0.6.5.1 with no other plugins
